plugins {
    id 'fabric-loom' version '1.11.8'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}


fabricApi {
    configureDataGeneration {
        client = true
    }
}

loom {
    accessWidenerPath = file("src/main/resources/slashblade.accesswidener")
    mixin {
        defaultRefmapName = "slashblade.refmap.json"
    }
    runs {
        datagen {
            property "fabric-api.datagen.modid", "slashblade"
        }
    }
}

repositories {
    flatDir {
        dir "libs"
    }
    mavenLocal()
    mavenCentral()
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        name = "Ladysnake Mods"
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {
        name "KosmX's maven"
        url 'https://maven.kosmx.dev/'
    }

    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }

    maven {
        url "https://cursemaven.com"
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url "https://maven.jamieswhiteshirt.com/libs-release"
        content {
            includeGroup "com.jamieswhiteshirt"
        }
    }
    maven { url = "https://mvn.devos.one/releases/" }
    maven { url = "https://mvn.devos.one/snapshots/" }
    // Patchouli
    maven { url = 'https://maven.blamejared.com' }
    maven {
        // 个人仓库，包含fork的PortingLib
        url = "https://raw.github.com/Sh1roCu/Sh1roCu_MCRepo/master/repository"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    //mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    mappings loom.layered() {
        officialMojangMappings()
        //parchment("org.parchmentmc.data:parchment-${project.parchment_minecraft_version}:${project.parchment_mappings_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // dependencies of all Porting-Lib modules
    modImplementation(include("io.github.fabricators_of_create.Porting-Lib:core:3.1.0-beta.79-fix+1.21.1-fix"))
    modImplementation(include("io.github.fabricators_of_create.Porting-Lib:gametest:3.1.0-beta.79-fix+1.21.1-fix"))

    modImplementation(include("io.github.fabricators_of_create.Porting-Lib:obj_loader:3.1.0-beta.79-fix+1.21.1-fix"))
    // dependencies of obj_loader
    modImplementation(include("io.github.fabricators_of_create.Porting-Lib:model_loader:3.1.0-beta.79-fix+1.21.1-fix"))
    modImplementation(include("io.github.fabricators_of_create.Porting-Lib:render_types:3.1.0-beta.79-fix+1.21.1-fix"))

    modImplementation(include("io.github.fabricators_of_create.Porting-Lib:entity:3.1.0-beta.79-fix+1.21.1-fix"))

    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
    annotationProcessor 'com.google.code.findbugs:jsr305:3.0.2'

    // CCA
    modImplementation(include("org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"))
    // CCA的item在1.21已弃用，使用原版的DataComponent代替
    // modImplementation(include("org.ladysnake.cardinal-components-api:cardinal-components-item:${project.cca_version}"))
    modImplementation(include("org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"))

    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:21.1.3"

    modImplementation "dev.kosmx.player-anim:player-animation-lib-fabric:2.0.1+1.21.1"
    //假人(含前置)
    modRuntimeOnly "curse.maven:selene-499980:7068423"
    modRuntimeOnly "curse.maven:mmmmmmmmmmmm-225738:6826532"
    // compile against the JEI API but do not include it at runtime
    modCompileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    modCompileOnly "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
    // at runtime, use the full JEI jar for Fabric
    modRuntimeOnly "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"

    //暮色森林
//    modCompileOnly ""

    modCompileOnly("vazkii.patchouli:Patchouli:1.21-87-FABRIC")
    modRuntimeOnly("vazkii.patchouli:Patchouli:1.21-87-FABRIC")

    modCompileOnly "curse.maven:emi-580555:6420930"
    modCompileOnly "dev.emi:emi-fabric:${emi_version}:api"
    modCompileOnly "dev.emi:emi-fabric:${emi_version}"

    modRuntimeOnly "curse.maven:nbtedit-reborn-678133:6125442"

    compileOnly "org.projectlombok:lombok:1.18.38"
    annotationProcessor "org.projectlombok:lombok:1.18.38"
    modImplementation "maven.modrinth:accrelatedrendering-refabricated:1.0.5-1.21.1-fabric.1"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = archives_base_name.toString().toLowerCase()
            from components.java
        }
    }

    repositories {
        maven {
            url "file:///D:/github_maven/Sh1roCu_MCRepo/repository"
        }
    }
}
