plugins {
    id 'net.fabricmc.fabric-loom' version '1.16-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}


fabricApi {
    configureDataGeneration {
        client = true
    }
}

loom {
    accessWidenerPath = file("src/main/resources/slashblade.classtweaker")
    mixin {
        defaultRefmapName = "slashblade.refmap.json"
    }
    runs {
        datagen {
            property "fabric-api.datagen.modid", "slashblade"
        }
    }
}

repositories {
    flatDir {
        dir "libs"
    }
    mavenLocal()
    mavenCentral()
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        name = "Ladysnake Mods"
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {
        name "KosmX's maven"
        url 'https://maven.kosmx.dev/'
    }

    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }

    maven {
        url "https://cursemaven.com"
    }
    maven {
        url = "https://api.modrinth.com/maven"
    }
    maven {
        url "https://maven.jamieswhiteshirt.com/libs-release"
        content {
            includeGroup "com.jamieswhiteshirt"
        }
    }
    maven { url = "https://mvn.devos.one/releases/" }
    maven { url = "https://mvn.devos.one/snapshots/" }
    // Patchouli
    maven { url = 'https://maven.blamejared.com' }
    maven {
        url = "https://raw.github.com/Sh1roCu/Sh1roCu_MCRepo/master/repository"
    }
    maven {
        name = "RedlanceMinecraft"
        url = "https://repo.redlance.org/public"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
    annotationProcessor 'com.google.code.findbugs:jsr305:3.0.2'

    // CCA
    implementation(include("org.ladysnake.cardinal-components-api:cardinal-components-base:${project.cca_version}"))
    // CCA的item在1.21已弃用，使用原版的DataComponent代替
    // implementation(include("org.ladysnake.cardinal-components-api:cardinal-components-item:${project.cca_version}"))
    implementation(include("org.ladysnake.cardinal-components-api:cardinal-components-entity:${project.cca_version}"))

    api "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:26.1.4"

    implementation "com.zigythebird.playeranim:PlayerAnimationLibFabric:1.2.4+mc.26.1"

    // compile against the JEI API but do not include it at runtime
    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
    // at runtime, use the full JEI jar for Fabric
    implementation "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"

    //暮色森林
//    compileOnly ""

    implementation("vazkii.patchouli:patchouli-fabric:26.1-94")

//    compileOnly "curse.maven:emi-580555:6420930"
//    compileOnly "dev.emi:emi-fabric:${emi_version}:api"
//    compileOnly "dev.emi:emi-fabric:${emi_version}"

    runtimeOnly "maven.modrinth:ankinbt:Rn3wocxw"

//    compileOnly "org.projectlombok:lombok:1.18.38"
//    annotationProcessor "org.projectlombok:lombok:1.18.38"
//    implementation "maven.modrinth:accrelatedrendering-refabricated:1.0.5-1.21.1-fabric.1"

    compileOnly "maven.modrinth:iris:1.11.2+26.1-fabric"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = archives_base_name.toString().toLowerCase()
            from components.java
        }
    }

    repositories {
        maven {
            url "file:///D:/github_maven/Sh1roCu_MCRepo/repository"
        }
    }
}
